; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

[env:mhetesp32devkit]
platform  = espressif32
board     = mhetesp32devkit
framework = arduino

; [env:esp32-s3-devkitc-1]
; platform = espressif32
; board = esp32-s3-devkitc-1
; framework = arduino
; upload_port = COM13
; monitor_port = COM13
upload_speed = 921600
monitor_speed = 115200
lib_deps =
 
  fastled/FastLED @ ^3.10.3

    ; ESP32Async/AsyncTCP
    ; ESP32Async/ESPAsyncWebServer
    ; https://github.com/LSatan/SmartRC-CC1101-Driver-Lib   
    ; lib/GyverWire-main.zip
    ; lib/rc-switch-master.zip
    ; lib/RadioHead-1.145.zip
    ; gyverlibs/GyverWire@^1.1.4  
    ; ; sui77/rc-switch@^2.6.4
build_flags = -DDEBUG_ESP_PORT=Serial

